services:
  postgres:
    image: postgres:15
    container_name: reservations_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    container_name: reservations_api
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
